import "./globals.css";
import { geistSans, geistMono } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="root">{children}</div>
      </body>
    </html>
  );
}
