import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="dns-prefetch" href="//cdn.jsdelivr.net" />
        <link rel="preconnect" href="https://cdn.jsdelivr.net" />
        <link rel="preload" href="https://cdn.jsdelivr.net/npm/@ui5/webcomponents-base@2.10.0/dist/jsx-runtime.js" as="script" />
        <link rel="prefetch" href="https://cdn.jsdelivr.net/npm/@ui5/webcomponents@2.10.0/" />
        <link rel="prefetch" href="https://cdn.jsdelivr.net/npm/@ui5/webcomponents-base@2.10.0/" />
        <link rel="prefetch" href="https://cdn.jsdelivr.net/npm/@ui5/webcomponents-fiori@2.10.0/" />
        <link rel="prefetch" href="https://cdn.jsdelivr.net/npm/lit-html@2" />

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
